/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HatcheriesRouteImport } from './routes/hatcheries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as HatcheriesSlugRouteImport } from './routes/hatcheries.$slug'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated/post'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardVerificationRouteImport } from './routes/_authenticated/dashboard.verification'
import { Route as AuthenticatedDashboardStoreRouteImport } from './routes/_authenticated/dashboard.store'
import { Route as AuthenticatedDashboardReservationsRouteImport } from './routes/_authenticated/dashboard.reservations'
import { Route as AuthenticatedDashboardQuotesRouteImport } from './routes/_authenticated/dashboard.quotes'
import { Route as AuthenticatedDashboardProviderRouteImport } from './routes/_authenticated/dashboard.provider'
import { Route as AuthenticatedDashboardHatcheryRouteImport } from './routes/_authenticated/dashboard.hatchery'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStoresRouteImport } from './routes/_authenticated/admin.stores'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminHatcheriesRouteImport } from './routes/_authenticated/admin.hatcheries'
import { Route as HatcheriesSlugBatchesBatchIdRouteImport } from './routes/hatcheries.$slug.batches.$batchId'
import { Route as AuthenticatedDashboardHatcheryOnboardingRouteImport } from './routes/_authenticated/dashboard.hatchery.onboarding'
import { Route as AuthenticatedDashboardHatcheryBookingsRouteImport } from './routes/_authenticated/dashboard.hatchery.bookings'
import { Route as AuthenticatedDashboardHatcheryBatchesRouteImport } from './routes/_authenticated/dashboard.hatchery.batches'
import { Route as AuthenticatedDashboardStoreAgroOnboardingRouteImport } from './routes/_authenticated/dashboard.store.agro.onboarding'
import { Route as AuthenticatedDashboardHatcheryBatchesBatchIdRouteImport } from './routes/_authenticated/dashboard.hatchery.batches.$batchId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HatcheriesRoute = HatcheriesRouteImport.update({
  id: '/hatcheries',
  path: '/hatcheries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const HatcheriesSlugRoute = HatcheriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HatcheriesRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardVerificationRoute =
  AuthenticatedDashboardVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStoreRoute =
  AuthenticatedDashboardStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReservationsRoute =
  AuthenticatedDashboardReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuotesRoute =
  AuthenticatedDashboardQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProviderRoute =
  AuthenticatedDashboardProviderRouteImport.update({
    id: '/provider',
    path: '/provider',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHatcheryRoute =
  AuthenticatedDashboardHatcheryRouteImport.update({
    id: '/hatchery',
    path: '/hatchery',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStoresRoute =
  AuthenticatedAdminStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHatcheriesRoute =
  AuthenticatedAdminHatcheriesRouteImport.update({
    id: '/hatcheries',
    path: '/hatcheries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const HatcheriesSlugBatchesBatchIdRoute =
  HatcheriesSlugBatchesBatchIdRouteImport.update({
    id: '/batches/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => HatcheriesSlugRoute,
  } as any)
const AuthenticatedDashboardHatcheryOnboardingRoute =
  AuthenticatedDashboardHatcheryOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedDashboardHatcheryRoute,
  } as any)
const AuthenticatedDashboardHatcheryBookingsRoute =
  AuthenticatedDashboardHatcheryBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardHatcheryRoute,
  } as any)
const AuthenticatedDashboardHatcheryBatchesRoute =
  AuthenticatedDashboardHatcheryBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedDashboardHatcheryRoute,
  } as any)
const AuthenticatedDashboardStoreAgroOnboardingRoute =
  AuthenticatedDashboardStoreAgroOnboardingRouteImport.update({
    id: '/agro/onboarding',
    path: '/agro/onboarding',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const AuthenticatedDashboardHatcheryBatchesBatchIdRoute =
  AuthenticatedDashboardHatcheryBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedDashboardHatcheryBatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hatcheries': typeof HatcheriesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/post': typeof AuthenticatedPostRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/hatcheries/$slug': typeof HatcheriesSlugRouteWithChildren
  '/listings/$id': typeof ListingsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/stores/': typeof StoresIndexRoute
  '/admin/hatcheries': typeof AuthenticatedAdminHatcheriesRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/dashboard/hatchery': typeof AuthenticatedDashboardHatcheryRouteWithChildren
  '/dashboard/provider': typeof AuthenticatedDashboardProviderRoute
  '/dashboard/quotes': typeof AuthenticatedDashboardQuotesRoute
  '/dashboard/reservations': typeof AuthenticatedDashboardReservationsRoute
  '/dashboard/store': typeof AuthenticatedDashboardStoreRouteWithChildren
  '/dashboard/verification': typeof AuthenticatedDashboardVerificationRoute
  '/dashboard/hatchery/batches': typeof AuthenticatedDashboardHatcheryBatchesRouteWithChildren
  '/dashboard/hatchery/bookings': typeof AuthenticatedDashboardHatcheryBookingsRoute
  '/dashboard/hatchery/onboarding': typeof AuthenticatedDashboardHatcheryOnboardingRoute
  '/hatcheries/$slug/batches/$batchId': typeof HatcheriesSlugBatchesBatchIdRoute
  '/dashboard/hatchery/batches/$batchId': typeof AuthenticatedDashboardHatcheryBatchesBatchIdRoute
  '/dashboard/store/agro/onboarding': typeof AuthenticatedDashboardStoreAgroOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hatcheries': typeof HatcheriesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/post': typeof AuthenticatedPostRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/hatcheries/$slug': typeof HatcheriesSlugRouteWithChildren
  '/listings/$id': typeof ListingsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/stores': typeof StoresIndexRoute
  '/admin/hatcheries': typeof AuthenticatedAdminHatcheriesRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/dashboard/hatchery': typeof AuthenticatedDashboardHatcheryRouteWithChildren
  '/dashboard/provider': typeof AuthenticatedDashboardProviderRoute
  '/dashboard/quotes': typeof AuthenticatedDashboardQuotesRoute
  '/dashboard/reservations': typeof AuthenticatedDashboardReservationsRoute
  '/dashboard/store': typeof AuthenticatedDashboardStoreRouteWithChildren
  '/dashboard/verification': typeof AuthenticatedDashboardVerificationRoute
  '/dashboard/hatchery/batches': typeof AuthenticatedDashboardHatcheryBatchesRouteWithChildren
  '/dashboard/hatchery/bookings': typeof AuthenticatedDashboardHatcheryBookingsRoute
  '/dashboard/hatchery/onboarding': typeof AuthenticatedDashboardHatcheryOnboardingRoute
  '/hatcheries/$slug/batches/$batchId': typeof HatcheriesSlugBatchesBatchIdRoute
  '/dashboard/hatchery/batches/$batchId': typeof AuthenticatedDashboardHatcheryBatchesBatchIdRoute
  '/dashboard/store/agro/onboarding': typeof AuthenticatedDashboardStoreAgroOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/hatcheries': typeof HatcheriesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/services': typeof ServicesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/post': typeof AuthenticatedPostRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/hatcheries/$slug': typeof HatcheriesSlugRouteWithChildren
  '/listings/$id': typeof ListingsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/stores/': typeof StoresIndexRoute
  '/_authenticated/admin/hatcheries': typeof AuthenticatedAdminHatcheriesRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/dashboard/hatchery': typeof AuthenticatedDashboardHatcheryRouteWithChildren
  '/_authenticated/dashboard/provider': typeof AuthenticatedDashboardProviderRoute
  '/_authenticated/dashboard/quotes': typeof AuthenticatedDashboardQuotesRoute
  '/_authenticated/dashboard/reservations': typeof AuthenticatedDashboardReservationsRoute
  '/_authenticated/dashboard/store': typeof AuthenticatedDashboardStoreRouteWithChildren
  '/_authenticated/dashboard/verification': typeof AuthenticatedDashboardVerificationRoute
  '/_authenticated/dashboard/hatchery/batches': typeof AuthenticatedDashboardHatcheryBatchesRouteWithChildren
  '/_authenticated/dashboard/hatchery/bookings': typeof AuthenticatedDashboardHatcheryBookingsRoute
  '/_authenticated/dashboard/hatchery/onboarding': typeof AuthenticatedDashboardHatcheryOnboardingRoute
  '/hatcheries/$slug/batches/$batchId': typeof HatcheriesSlugBatchesBatchIdRoute
  '/_authenticated/dashboard/hatchery/batches/$batchId': typeof AuthenticatedDashboardHatcheryBatchesBatchIdRoute
  '/_authenticated/dashboard/store/agro/onboarding': typeof AuthenticatedDashboardStoreAgroOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/hatcheries'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/services'
    | '/admin'
    | '/dashboard'
    | '/post'
    | '/saved'
    | '/hatcheries/$slug'
    | '/listings/$id'
    | '/services/$slug'
    | '/stores/$slug'
    | '/stores/'
    | '/admin/hatcheries'
    | '/admin/listings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/verifications'
    | '/dashboard/hatchery'
    | '/dashboard/provider'
    | '/dashboard/quotes'
    | '/dashboard/reservations'
    | '/dashboard/store'
    | '/dashboard/verification'
    | '/dashboard/hatchery/batches'
    | '/dashboard/hatchery/bookings'
    | '/dashboard/hatchery/onboarding'
    | '/hatcheries/$slug/batches/$batchId'
    | '/dashboard/hatchery/batches/$batchId'
    | '/dashboard/store/agro/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/hatcheries'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/services'
    | '/admin'
    | '/dashboard'
    | '/post'
    | '/saved'
    | '/hatcheries/$slug'
    | '/listings/$id'
    | '/services/$slug'
    | '/stores/$slug'
    | '/stores'
    | '/admin/hatcheries'
    | '/admin/listings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/verifications'
    | '/dashboard/hatchery'
    | '/dashboard/provider'
    | '/dashboard/quotes'
    | '/dashboard/reservations'
    | '/dashboard/store'
    | '/dashboard/verification'
    | '/dashboard/hatchery/batches'
    | '/dashboard/hatchery/bookings'
    | '/dashboard/hatchery/onboarding'
    | '/hatcheries/$slug/batches/$batchId'
    | '/dashboard/hatchery/batches/$batchId'
    | '/dashboard/store/agro/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/hatcheries'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/post'
    | '/_authenticated/saved'
    | '/hatcheries/$slug'
    | '/listings/$id'
    | '/services/$slug'
    | '/stores/$slug'
    | '/stores/'
    | '/_authenticated/admin/hatcheries'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/stores'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/dashboard/hatchery'
    | '/_authenticated/dashboard/provider'
    | '/_authenticated/dashboard/quotes'
    | '/_authenticated/dashboard/reservations'
    | '/_authenticated/dashboard/store'
    | '/_authenticated/dashboard/verification'
    | '/_authenticated/dashboard/hatchery/batches'
    | '/_authenticated/dashboard/hatchery/bookings'
    | '/_authenticated/dashboard/hatchery/onboarding'
    | '/hatcheries/$slug/batches/$batchId'
    | '/_authenticated/dashboard/hatchery/batches/$batchId'
    | '/_authenticated/dashboard/store/agro/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  HatcheriesRoute: typeof HatcheriesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StoresSlugRoute: typeof StoresSlugRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatcheries': {
      id: '/hatcheries'
      path: '/hatcheries'
      fullPath: '/hatcheries'
      preLoaderRoute: typeof HatcheriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/hatcheries/$slug': {
      id: '/hatcheries/$slug'
      path: '/$slug'
      fullPath: '/hatcheries/$slug'
      preLoaderRoute: typeof HatcheriesSlugRouteImport
      parentRoute: typeof HatcheriesRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/verification': {
      id: '/_authenticated/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof AuthenticatedDashboardVerificationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/store': {
      id: '/_authenticated/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof AuthenticatedDashboardStoreRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reservations': {
      id: '/_authenticated/dashboard/reservations'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof AuthenticatedDashboardReservationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/quotes': {
      id: '/_authenticated/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof AuthenticatedDashboardQuotesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/provider': {
      id: '/_authenticated/dashboard/provider'
      path: '/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof AuthenticatedDashboardProviderRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/hatchery': {
      id: '/_authenticated/dashboard/hatchery'
      path: '/hatchery'
      fullPath: '/dashboard/hatchery'
      preLoaderRoute: typeof AuthenticatedDashboardHatcheryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stores': {
      id: '/_authenticated/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hatcheries': {
      id: '/_authenticated/admin/hatcheries'
      path: '/hatcheries'
      fullPath: '/admin/hatcheries'
      preLoaderRoute: typeof AuthenticatedAdminHatcheriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/hatcheries/$slug/batches/$batchId': {
      id: '/hatcheries/$slug/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/hatcheries/$slug/batches/$batchId'
      preLoaderRoute: typeof HatcheriesSlugBatchesBatchIdRouteImport
      parentRoute: typeof HatcheriesSlugRoute
    }
    '/_authenticated/dashboard/hatchery/onboarding': {
      id: '/_authenticated/dashboard/hatchery/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/hatchery/onboarding'
      preLoaderRoute: typeof AuthenticatedDashboardHatcheryOnboardingRouteImport
      parentRoute: typeof AuthenticatedDashboardHatcheryRoute
    }
    '/_authenticated/dashboard/hatchery/bookings': {
      id: '/_authenticated/dashboard/hatchery/bookings'
      path: '/bookings'
      fullPath: '/dashboard/hatchery/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardHatcheryBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardHatcheryRoute
    }
    '/_authenticated/dashboard/hatchery/batches': {
      id: '/_authenticated/dashboard/hatchery/batches'
      path: '/batches'
      fullPath: '/dashboard/hatchery/batches'
      preLoaderRoute: typeof AuthenticatedDashboardHatcheryBatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardHatcheryRoute
    }
    '/_authenticated/dashboard/store/agro/onboarding': {
      id: '/_authenticated/dashboard/store/agro/onboarding'
      path: '/agro/onboarding'
      fullPath: '/dashboard/store/agro/onboarding'
      preLoaderRoute: typeof AuthenticatedDashboardStoreAgroOnboardingRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/_authenticated/dashboard/hatchery/batches/$batchId': {
      id: '/_authenticated/dashboard/hatchery/batches/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/hatchery/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedDashboardHatcheryBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedDashboardHatcheryBatchesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminHatcheriesRoute: typeof AuthenticatedAdminHatcheriesRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminStoresRoute: typeof AuthenticatedAdminStoresRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminHatcheriesRoute: AuthenticatedAdminHatcheriesRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminStoresRoute: AuthenticatedAdminStoresRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardHatcheryBatchesRouteChildren {
  AuthenticatedDashboardHatcheryBatchesBatchIdRoute: typeof AuthenticatedDashboardHatcheryBatchesBatchIdRoute
}

const AuthenticatedDashboardHatcheryBatchesRouteChildren: AuthenticatedDashboardHatcheryBatchesRouteChildren =
  {
    AuthenticatedDashboardHatcheryBatchesBatchIdRoute:
      AuthenticatedDashboardHatcheryBatchesBatchIdRoute,
  }

const AuthenticatedDashboardHatcheryBatchesRouteWithChildren =
  AuthenticatedDashboardHatcheryBatchesRoute._addFileChildren(
    AuthenticatedDashboardHatcheryBatchesRouteChildren,
  )

interface AuthenticatedDashboardHatcheryRouteChildren {
  AuthenticatedDashboardHatcheryBatchesRoute: typeof AuthenticatedDashboardHatcheryBatchesRouteWithChildren
  AuthenticatedDashboardHatcheryBookingsRoute: typeof AuthenticatedDashboardHatcheryBookingsRoute
  AuthenticatedDashboardHatcheryOnboardingRoute: typeof AuthenticatedDashboardHatcheryOnboardingRoute
}

const AuthenticatedDashboardHatcheryRouteChildren: AuthenticatedDashboardHatcheryRouteChildren =
  {
    AuthenticatedDashboardHatcheryBatchesRoute:
      AuthenticatedDashboardHatcheryBatchesRouteWithChildren,
    AuthenticatedDashboardHatcheryBookingsRoute:
      AuthenticatedDashboardHatcheryBookingsRoute,
    AuthenticatedDashboardHatcheryOnboardingRoute:
      AuthenticatedDashboardHatcheryOnboardingRoute,
  }

const AuthenticatedDashboardHatcheryRouteWithChildren =
  AuthenticatedDashboardHatcheryRoute._addFileChildren(
    AuthenticatedDashboardHatcheryRouteChildren,
  )

interface AuthenticatedDashboardStoreRouteChildren {
  AuthenticatedDashboardStoreAgroOnboardingRoute: typeof AuthenticatedDashboardStoreAgroOnboardingRoute
}

const AuthenticatedDashboardStoreRouteChildren: AuthenticatedDashboardStoreRouteChildren =
  {
    AuthenticatedDashboardStoreAgroOnboardingRoute:
      AuthenticatedDashboardStoreAgroOnboardingRoute,
  }

const AuthenticatedDashboardStoreRouteWithChildren =
  AuthenticatedDashboardStoreRoute._addFileChildren(
    AuthenticatedDashboardStoreRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardHatcheryRoute: typeof AuthenticatedDashboardHatcheryRouteWithChildren
  AuthenticatedDashboardProviderRoute: typeof AuthenticatedDashboardProviderRoute
  AuthenticatedDashboardQuotesRoute: typeof AuthenticatedDashboardQuotesRoute
  AuthenticatedDashboardReservationsRoute: typeof AuthenticatedDashboardReservationsRoute
  AuthenticatedDashboardStoreRoute: typeof AuthenticatedDashboardStoreRouteWithChildren
  AuthenticatedDashboardVerificationRoute: typeof AuthenticatedDashboardVerificationRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardHatcheryRoute:
      AuthenticatedDashboardHatcheryRouteWithChildren,
    AuthenticatedDashboardProviderRoute: AuthenticatedDashboardProviderRoute,
    AuthenticatedDashboardQuotesRoute: AuthenticatedDashboardQuotesRoute,
    AuthenticatedDashboardReservationsRoute:
      AuthenticatedDashboardReservationsRoute,
    AuthenticatedDashboardStoreRoute:
      AuthenticatedDashboardStoreRouteWithChildren,
    AuthenticatedDashboardVerificationRoute:
      AuthenticatedDashboardVerificationRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedPostRoute: typeof AuthenticatedPostRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedPostRoute: AuthenticatedPostRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HatcheriesSlugRouteChildren {
  HatcheriesSlugBatchesBatchIdRoute: typeof HatcheriesSlugBatchesBatchIdRoute
}

const HatcheriesSlugRouteChildren: HatcheriesSlugRouteChildren = {
  HatcheriesSlugBatchesBatchIdRoute: HatcheriesSlugBatchesBatchIdRoute,
}

const HatcheriesSlugRouteWithChildren = HatcheriesSlugRoute._addFileChildren(
  HatcheriesSlugRouteChildren,
)

interface HatcheriesRouteChildren {
  HatcheriesSlugRoute: typeof HatcheriesSlugRouteWithChildren
}

const HatcheriesRouteChildren: HatcheriesRouteChildren = {
  HatcheriesSlugRoute: HatcheriesSlugRouteWithChildren,
}

const HatcheriesRouteWithChildren = HatcheriesRoute._addFileChildren(
  HatcheriesRouteChildren,
)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  HatcheriesRoute: HatcheriesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StoresSlugRoute: StoresSlugRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
